global:
  appEnv: local
  logLevel: debug
  image:
    repository: malus-be
    separator: /
    tag: local
    pullPolicy: Never
  workloadIdentity: false

networkPolicy:
  extraEgressPorts: [8081]

services:
  gateway:
    service:
      type: NodePort
      nodePort: 30080
      externalTrafficPolicy: null
    autoscaling:
      enabled: false
    env:
      AUTH_DISABLED: "true"
      CORS_ALLOWED_ORIGINS: http://localhost:5173

  content:
    secretEnv:
      SQL_DSN: server=sqlserver.malus-deps.svc.cluster.local;port=1433;user id=sa;password=Malus-local-Passw0rd;database=malus_content;encrypt=true;TrustServerCertificate=true

  interaction:
    env:
      COSMOS_ENDPOINT: http://cosmos.malus-deps.svc.cluster.local:8081
      COSMOS_DATABASE: malus
      COSMOS_QUESTIONS_CONTAINER: questions
    secretEnv:
      COSMOS_KEY: C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw==

  realtime:
    autoscaling:
      enabled: false
